from enum import auto, IntEnum


class Request(IntEnum):
    STAGE_TIMING = 1
    STG_TIME = 1
    STAGE_SEQUENCE_RANDOM = 2
    STG_SEQ_RAND = 2
    STAGE_SEQUENCE_REGULAR = 3
    STG_SEQ_REG = 3
    START_SEQUENCE = 4
    START = 4
    STOP_SEQUENCE = 5
    STOP = 5
    QUERY_SEQUENCE_PROGRESS = 6
    Q_SEQ_PROG = 6
    QUERY_STAGED_TIMING = 7
    Q_STG_TIME = 7
    QUERY_STAGED_SEQUENCE = 8
    Q_STG_SEQ = 8
    QUERY_COMMITTED_TIMING = 9
    Q_CMT_TIME = 9
    QUERY_COMMITTED_SEQUENCE = 10
    Q_CMT_SEQ = 10


class Response(IntEnum):
    SUCCESS = 1
    FAILURE = 2
